services:
  db:
    container_name: db_lesson
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .development.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  lesson-backend:
    build: 
      context: .
    env_file:
      - .development.env
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    restart: always